cases_sct = [
	{ 'name': 'Gill v. Whitford', 'case_number':'16-285' },
	{ 'name': 'Trump v. Hawaii', 'case_number':'17-965' },
	{ 'name': 'Abbott v. Perez', 'case_number':'17-626' },
	{ 'name': 'Abbott v. Perez', 'case_number':'17-586' },
	{ 'name': 'Masterpiece Cake Shop v. Colorado Civil Rights Comm\'n', 'case_number':'16-111' },
	{ 'name': 'Carpenter v. United States', 'case_number':'16-402' },
	{ 'name': 'Christie v. NCAA', 'case_number':'16-476' },
	{ 'name': 'Rubin v. Iran', 'case_number':'16-534' },
	{ 'name': 'Byrd v. United States', 'case_number':'16-1371' },
	{ 'name': 'Collins v. Virginia', 'case_number':'16-1072' },
	{ 'name': 'Dalmazzi v. United States', 'case_number':'16-961' },
	{ 'name': 'McCoy v. Louisiana', 'case_number':'16-1362' },
	{ 'name': 'City of Hays v. Vogt', 'case_number':'16-1495' },
	{ 'name': 'Currier v. Virginia', 'case_number':'16-1348' },
	{ 'name': 'Dahda v. United States', 'case_number':'17-43' },
	{ 'name': 'Janus v. AFSCME Council 31', 'case_number':'16-1466' },
	{ 'name': 'United States v. Microsoft', 'case_number':'17-2' },
	{ 'name': 'Lozman v. Riviera Beach, Fla.', 'case_number':'17-21' },
	{ 'name': 'Minnesota Voters Alliance v. Mansky', 'case_number':'16-1435' },
	{ 'name': 'Sveen v. Melin', 'case_number':'16-1432' },
	{ 'name': 'Nat\'l Inst. of Family and Life v. Becerra', 'case_number':'16-1140' },
	{ 'name': 'Lucia v. SEC', 'case_number':'17-130' },
	{ 'name': 'Benisek v. Lamone', 'case_number':'17-333' },
]

cases = [
	{ 'name':  'Mass. travel EO case', 'case_number': '1:17-cv-10154', 'court': 'D. Mass.' },
	{ 'name': 'EDNY travel EO case', 'case_number': '1:17-cv-00480', 'court':'E.D.N.Y.' },
	{ 'name': 'Calif. travel EO case', 'case_number':'2:17-cv-00702', 'court':'C.D. Cal.' },
	{ 'name': 'Wash. travel EO case', 'case_number':'2:17-cv-00126', 'court':'W.D. Wash.' },
	{ 'name': 'US v. Joaquin Guzman', 'case_number':'1:09-cr-00466-4', 'court':'E.D.N.Y.' },
	{ 'name': 'Asgari v. Trump', 'case_number':'1:17-cv-10182', 'court':'D. Mass.' },
	{ 'name': 'Washington v. Trump', 'case_number':'2:17-cv-00141','court':'W.D. Wash.'},
	{ 'name':'Calif. v. Trump', 'case_number':'3:17-cv-00451', 'court':'N.D. Cal.'},
	{ 'name':'Mowafak v. Trump', 'case_number':'3:17-cv-00557', 'court':'N.D. Cal.' },
	{ 'name':'Hagig v. Trump','case_number':'1:17-cv-00289', 'court':'D. Colo.' },
	{ 'name':'Mohammed v. USA', 'case_number':'2:17-cv-00786', 'court':'C.D. Cal.'},
	{ 'name':'ACRL v. Trump', 'case_number':'2:17-cv-10310', 'court':'E.D. Mich.' },
	{ 'name':'Zadeh v. Trump (DC)', 'case_number':'1:17-cv-00243', 'court':'D.D.C.' },
	{ 'name':'PARS v. Trump', 'case_number':'1:17-cv-00255', 'court':'D.D.C.' },
	{ 'name':'In re Google Search Warrant', 'case_number':'2:16-mj-01061-1', 'court':'E.D. Pa.' },
	{ 'name':'In re Google Accounts', 'case_number':'2:16-mj-00960-1', 'court':'E.D. Pa.' },
	{ 'name':'Unite Oregon v. Trump', 'case_number':'3:17-cv-00179', 'court':'D. Ore.' },
	{ 'name':'Alknfushe v. Trump', 'case_number':'1:17-cv-00483', 'court':'E.D.N.Y.' },
	{ 'name':'#DAPL case', 'case_number':'1:16-cv-01534', 'court':'D.D.C.' },
	{ 'name':'Doe v. Trump', 'case_number':'3:17-cv-00112', 'court':'W.D. Wis.' },
	{ 'name':'Medina v. Homeland Security', 'case_number':'2:17-cv-00218', 'court':'W.D. Wash.' },
	{ 'name':'Texas voter ID case', 'case_number':'2:13-cv-00193', 'court':'S.D. Texas' },
	{ 'name':'San Francisco v. Trump', 'case_number':'3:17-cv-00485','court':'N.D. Cal.' },
	{ 'name':'Seattle v. Trump', 'case_number':'2:17-cv-00497', 'court':'W.D. Wash.' },
	{ 'name':'City of Richmond v. Trump', 'case_number':'3:17-cv-01535', 'court':'N.D. Cal.' },
	{ 'name':'Chelsea and Lawrence, Mass. v. Trump', 'case_number':'1:17-cv-10214', 'court':'D. Mass.' },
	{ 'name':'John and Jane Doe v. Trump', 'case_number':'1:17-cv-00537', 'court':'D.D.C.' },
	{ 'name':'@USATODAY, @AP, @VICE v. DOJ (iPhone crack)', 'case_number':'1:16-cv-01850', 'court':'D.D.C.' },
	{ 'name':'Trump FISA info #FOIA case',  'case_number':'1:17-cv-00597', 'court':'D.D.C.' },
	{ 'name':'ACLU v. Madison County, Miss.', 'case_number':'3:17-cv-00347', 'court':'S.D. Miss.' }, 
	{ 'name':'Trump University case', 'case_number':'3:13-cv-02519', 'court':'S.D. Cal.' },
	{ 'name':'CREW v. Trump Emoluments case', 'case_number':'1:17-cv-00458', 'court':'S.D.N.Y.' },
	{ 'name':'Nwanguma et al v. Trump', 'case_number':'3:16-cv-00247', 'court':'W.D. Ky.' },
	{ 'name':'@USATODAY v. DOJ (Comey memos)', 'case_number':'1:17-cv-01175', 'court':'D.D.C.' },
	{ 'name':'@NYTimes v. FBI (Comey memos)', 'case_number':'1:17-cv-04558','court':'S.D.N.Y.' },
	{ 'name': '@CNN, @USATODAY et al. v. FBI (Comey memos)', 'case_number':'1:17-cv-01167', 'court':'D.D.C.' },
	{ 'name': '@EPICPrivacy v. Election Integrity Commn\'n', 'case_number':'1:17-cv-01320', 'court':'D.D.C.' },
	{ 'name': 'United States v. @SenatorMenendez', 'case_number':'2:15-cr-00155-1', 'court':'D.N.J.' },
	{ 'name': 'Cockrum v. Trump', 'case_number':'1:17-cv-01370', 'court':'D.D.C.' },
	{ 'name':'Sen. Blumenthal et al., v. Trump', 'case_number':'1:17-cv-01154', 'court':'D.D.C.' },
	{ 'name':'Knight Institute v. Trump', 'case_number':'1:17-cv-05205', 'court':'S.D.N.Y.' },
	{ 'name':'United States v. Arpaio',  'case_number':'2:16-cr-01012-1', 'court':'D. Ariz.' },
	{ 'name':'United States v. Apple Macbook', 'case_number':'2:15-mj-00850-1', 'court':'E.D. Pa.' },
	{ 'name':'Rod Wheeler v. @FoxNews et al.', 'case_number':'1:17-cv-05807', 'court':'S.D.N.Y.' },
	{ 'name':'Chicago v. Sessions (Sanctuary cities EO)', 'case_number':'1:17-cv-05720', 'court':'N.D. Ill.' },
	{ 'name':'Marshal Coal v. @iamjohnoliver', 'case_number':'5:17-cv-00099',  'court':'N.D. W.Va.' },
	{ 'name':'@SarahPalinUSA v. @NYTimes', 'case_number':'1:17-cv-04853', 'court':'S.D.N.Y.' },
	{ 'name':'Horse v. D.C.', 'case_number':'1:17-cv-01216', 'court':'D.D.C.' },
	{ 'name':'United States v. @MalwareTechBlog', 'case_number':'2:17-cr-00124-2', 'court':'E.D. Wis.' },
	{ 'name':'@ACLU_NorCal v. Sessions', 'case_number':'3:17-cv-03615', 'court':'N.D. Cal.' },
	{'name':'@benjaminwittes v. DOJ', 'case_number':'1:17-cv-01627', 'court':'D.D.C.' },
	{'name':'United States v. Varnell', 'case_number':'5:17-mj-00368-1','court':'W.D. Okla.' },
	{ 'name':'San Francisco v. Sessions', 'case_number':'3:17-cv-04642', 'court':'N.D. Cal.' },
	{ 'name':'Texas v. United States (DACA)', 'case_number':'1:14-cv-00254', 'court':'S.D. Texas' },
	{ 'name':'@NYTimes v. @CIA', 'case_number':'1:17-cv-06354', 'court':'S.D.N.Y.' },
	{ 'name':'PACER fees case', 'case_number':'1:16-cv-00745', 'court':'D.D.C.' },
	{ 'name':'New York v. Trump (#DACA challenge)', 'case_number':'1:17-cv-05228', 'court':'E.D.N.Y.' },
	{ 'name':'United States v. Martin Shkreli', 'case_number':'1:15-cr-00637-1', 'court':'E.D.N.Y.' },
	{ 'name':'Doyle v. DHS (Trump visitor logs)' ,'case_number':'1:17-cv-02542', 'court':'S.D.N.Y.' },
	{ 'name':'California v. Trump (ACA cost-sharing)', 'case_number': '3:17-cv-05895', 'court':'N.D. Cal.' },
	{ 'name':'Garza v. Hargan', 'case_number':'1:17-cv-02122', 'court':'D.D.C.' },
	{ 'name':'Garza v. Hargan (D.C. Cir.)', 'case_number':'17-5236', 'court':'D.C. Cir.' },
	{ 'name':'United States v. Manafort', 'case_number':'1:17-cr-00201-1', 'court':'D.D.C.' },
	{ 'name':'United States v. Gates', 'case_number':'1:17-cr-00201-2', 'court':'D.D.C.' },
	{ 'name':'United States v. Papadopoulos', 'case_number':'1:17-cr-00182-1', 'court':'D.D.C.' },
	{ 'name':'United States v. Saipov', 'case_number':'1:17-mj-08177', 'court':'S.D.N.Y.' },
	{ 'name':'In re subpoena to Fusion GPS', 'case_number':'1:17-mc-02171', 'court':'D.D.C.' },
	{ 'name':'Fridman v. Fusion GPS', 'case_number':'1:17-cv-02041', 'court':'D.D.C.' },
	{ 'name':'Fusion GPS v. John Doe Bank', 'case_number':'1:17-cv-02187', 'court':'D.D.C.' },
	{ 'name':'United States v. AT&T and Time Warner', 'case_number':'1:17-cv-02511', 'court':'D.D.C.' },
	{ 'name':'English v. Trump', 'case_number':'1:17-cv-02534', 'court':'D.D.C.' },
	{ 'name':'Freedom Watch v. Sessions', 'case_number':'1:17-cv-02459', 'court':'D.D.C.' }, 
	{ 'name':'Waymo v. @Uber', 'case_number':'3:17-cv-00939', 'court':'N.D. Cal.' },
	{'name':'@ACLU v. Mattis', 'case_number':'1:17-cv-02069', 'court':'D.D.C.' },
	{'name':'United States v. Mike Flynn','case_number':'1:17-cr-00232-1', 'court':'D.D.C.' },
	{'name':'Manafort v. DOJ, Mueller', 'case_number':'1:18-cv-00011', 'court':'D.D.C.' },
	
]