cases = [
	{ 'name':  'Mass. travel EO case', 'case_number': '1:17-cv-10154', 'court': 'D. Mass.' },
	{ 'name': 'EDNY travel EO case', 'case_number': '1:17-cv-00480', 'court':'E.D.N.Y.' },
	{ 'name': 'Calif. travel EO case', 'case_number':'2:17-cv-00702', 'court':'C.D. Cal.' },
	{ 'name': 'Wash. travel EO case', 'case_number':'2:17-cv-00126', 'court':'W.D. Wash.' },
	{ 'name': 'US v. Joaquin Guzman', 'case_number':'1:09-cr-00466-4', 'court':'E.D.N.Y.' },
	{ 'name': 'Asgari v. Trump', 'case_number':'1:17-cv-10182', 'court':'D. Mass.' },
	{ 'name': 'Washington v. Trump', 'case_number':'2:17-cv-00141','court':'W.D. Wash.'},
	{ 'name':'Calif. v. Trump', 'case_number':'3:17-cv-00451', 'court':'N.D. Cal.'},
	{ 'name':'Mowafak v. Trump', 'case_number':'3:17-cv-00557', 'court':'N.D. Cal.' },
	{ 'name':'Hagig v. Trump','case_number':'1:17-cv-00289', 'court':'D. Colo.' },
	{ 'name':'Mohammed v. USA', 'case_number':'2:17-cv-00786', 'court':'C.D. Cal.'},
	{ 'name':'ACRL v. Trump', 'case_number':'2:17-cv-10310', 'court':'E.D. Mich.' },
	{ 'name':'Zadeh v. Trump (DC)', 'case_number':'1:17-cv-00243', 'court':'D.D.C.' },
	{ 'name':'PARS v. Trump', 'case_number':'1:17-cv-00255', 'court':'D.D.C.' },
	{ 'name':'In re Google Search Warrant', 'case_number':'2:16-mj-01061-1', 'court':'E.D. Pa.' },
	{ 'name':'In re Google Accounts', 'case_number':'2:16-mj-00960-1', 'court':'E.D. Pa.' },
	{ 'name':'Unite Oregon v. Trump', 'case_number':'3:17-cv-00179', 'court':'D. Ore.' },
	{ 'name':'Alknfushe v. Trump', 'case_number':'1:17-cv-00483', 'court':'E.D.N.Y.' },
	{ 'name':'#DAPL case', 'case_number':'1:16-cv-01534', 'court':'D.D.C.' },
	{ 'name':'Doe v. Trump', 'case_number':'3:17-cv-00112', 'court':'W.D. Wis.' },
	{ 'name':'Medina v. Homeland Security', 'case_number':'2:17-cv-00218', 'court':'W.D. Wash.' },
	{ 'name':'Texas voter ID case', 'case_number':'2:13-cv-00193', 'court':'S.D. Texas' },
	{ 'name':'San Francisco v. Trump', 'case_number':'3:17-cv-00485','court':'N.D. Cal.' },
	{ 'name':'Seattle v. Trump', 'case_number':'2:17-cv-00497', 'court':'W.D. Wash.' },
	{ 'name':'City of Richmond v. Trump', 'case_number':'3:17-cv-01535', 'court':'N.D. Cal.' },
	{ 'name':'Chelsea and Lawrence, Mass. v. Trump', 'case_number':'1:17-cv-10214', 'court':'D. Mass.' },
	{ 'name':'John and Jane Doe v. Trump', 'case_number':'1:17-cv-00537', 'court':'D.D.C.' },
	{ 'name':'@USATODAY, @AP, @VICE v. DOJ (iPhone crack)', 'case_number':'1:16-cv-01850', 'court':'D.D.C.' },
	{ 'name':'Trump FISA info #FOIA case',  'case_number':'1:17-cv-00597', 'court':'D.D.C.' },
	{ 'name':'ACLU v. Brown County, Miss.', 'case_number':'3:17-cv-00347', 'court':'S.D. Miss.' }, 
	{ 'name':'Trump University case', 'case_number':'3:13-cv-02519', 'court':'S.D. Cal.' },
	{ 'name':'CREW v. Trump Emoluments case', 'case_number':'1:17-cv-00458', 'court':'S.D.N.Y.' },
	{ 'name':'Nwanguma et al v. Trump', 'case_number':'3:16-cv-00247', 'court':'W.D. Ky.' },
	{ 'name':'@USATODAY v. DOJ (Comey memos)', 'case_number':'1:17-cv-01175', 'court':'D.D.C.' },
	{ 'name':'@NYTimes v. FBI (Comey memos)', 'case_number':'1:17-cv-04558','court':'S.D.N.Y.' },
	{ 'name': '@CNN, @USATODAY et al. v. FBI (Comey memos)', 'case_number':'1:17-cv-01167', 'court':'D.D.C.' },
	{ 'name': '@EPICPrivacy v. Election Integrity Commn\'n', 'case_number':'1:17-cv-01320', 'court':'D.D.C.' },
	{ 'name': 'Cockrum v. Trump', 'case_number':'1:17-cv-01370', 'court':'D.D.C.' },
	{ 'name':'Sen. Blumenthal et al., v. Trump', 'case_number':'1:17-cv-01154', 'court':'D.D.C.' },
	{ 'name':'Knight Institute v. Trump', 'case_number':'1:17-cv-05205', 'court':'S.D.N.Y.' },
	{ 'name':'United States v. Arpaio',  'case_number':'2:16-cr-01012-1', 'court':'D. Ariz.' },
	{ 'name':'United States v. Apple Macbook', 'case_number':'2:15-mj-00850-1', 'court':'E.D. Pa.' },
	{ 'name':'Rod Wheeler v. @FoxNews et al.', 'case_number':'1:17-cv-05807', 'court':'S.D.N.Y.' },
	{ 'name':'Chicago v. Sessions (Sanctuary cities EO)', 'case_number':'1:17-cv-05720', 'court':'N.D. Ill.' },
	{ 'name':'Marshal Coal v. @iamjohnoliver', 'case_number':'5:17-cv-00099',  'court':'N.D. W.Va.' },
]