cases = [
	{ 'name':  'Mass. travel EO case', 'case_number': '1:17-cv-10154', 'court': 'D. Mass.' },
	{ 'name': 'EDNY travel EO case', 'case_number': '1:17-cv-00480', 'court':'E.D.N.Y.' },
	{ 'name': 'Calif. travel EO case', 'case_number':'2:17-cv-00702', 'court':'C.D. Cal.' },
	{ 'name': 'Wash. travel EO case', 'case_number':'2:17-cv-00126', 'court':'W.D. Wash.' },
	{ 'name': 'US v. Joaquin Guzman', 'case_number':'1:09-cr-00466-4', 'court':'E.D.N.Y.' },
	{ 'name': 'Asgari v. Trump', 'case_number':'1:17-cv-10182', 'court':'D. Mass.' },
	{ 'name': 'Washington v. Trump', 'case_number':'2:17-cv-00141','court':'W.D. Wash.'},
	{ 'name':'Calif. v. Trump', 'case_number':'3:17-cv-00451', 'court':'N.D. Cal.'},
	{ 'name':'Mowafak v. Trump', 'case_number':'3:17-cv-00557', 'court':'N.D. Cal.' },
	{ 'name':'Hagig v. Trump','case_number':'1:17-cv-00289', 'court':'D. Colo.' },
	{ 'name':'Mohammed v. USA', 'case_number':'2:17-cv-00786', 'court':'C.D. Cal.'},
	{ 'name':'ACRL v. Trump', 'case_number':'2:17-cv-10310', 'court':'E.D. Mich.' },
	{ 'name':'Zadeh v. Trump (DC)', 'case_number':'1:17-cv-00243', 'court':'D.D.C.' },
	{ 'name':'PARS v. Trump', 'case_number':'1:17-cv-00255', 'court':'D.D.C.' },
	{ 'name':'In re Google Search Warrant', 'case_number':'2:16-mj-01061-1', 'court':'E.D. Pa.' },
	{ 'name':'In re Google Accounts', 'case_number':'2:16-mj-00960-1', 'court':'E.D. Pa.' },
	{ 'name':'Unite Oregon v. Trump', 'case_number':'3:17-cv-00179', 'court':'D. Ore.' },
	{ 'name':'Alknfushe v. Trump', 'case_number':'1:17-cv-00483', 'court':'E.D.N.Y.' },
	{ 'name':'#DAPL case', 'case_number':'1:16-cv-01534', 'court':'D.D.C.' },
	{ 'name':'Doe v. Trump', 'case_number':'3:17-cv-00112', 'court':'W.D. Wis.' },
	{ 'name':'Medina v. Homeland Security', 'case_number':'2:17-cv-00218', 'court':'W.D. Wash.' },
	{ 'name':'Texas voter ID case', 'case_number':'2:13-cv-00193', 'court':'S.D. Texas' },
	{ 'name':'San Francisco v. Trump', 'case_number':'3:17-cv-00485','court':'N.D. Cal.' },
]