courts = [

		# Circuit courts
		{ 'id': 'D.C. Cir.', 'url':'https://ecf.cadc.uscourts.gov/cmecf/servlet/TransportRoom?servlet=RSSGenerator' },
		{ 'id': '2d. Cir.', 'url' : 'https://ecf.ca2.uscourts.gov/n/beam/servlet/TransportRoom?servlet=RSSGenerator' },
		{ 'id': '6th Cir.', 'url': 'https://ecf.ca6.uscourts.gov/cmecf/servlet/TransportRoom?servlet=RSSGenerator' },
		{ 'id': '10th Cir.', 'url': 'https://ecf.ca10.uscourts.gov/cmecf/servlet/TransportRoom?servlet=RSSGenerator' },
		{ 'id': 'Fed. Cir.', 'url' : 'https://ecf.cafc.uscourts.gov/cmecf/servlet/TransportRoom?servlet=RSSGenerator' },

		# District courts
		{ 'id': 'M.D. Ala.', 'url': 'https://ecf.almd.uscourts.gov/cgi-bin/rss_outside.pl' },
		{ 'id': 'S.D. Ala.', 'url':'https://ecf.alsd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'D. Alaska', 'url':'https://ecf.akd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'E.D. Ark.', 'url':'https://ecf.ared.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'W.D. Ark.', 'url':'https://ecf.arwd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'C.D. Cal.', 'url':'https://ecf.cacd.uscourts.gov/cgi-bin/rss_outside.pl' },
		{ 'id': 'N.D. Cal.', 'url':'https://ecf.cand.uscourts.gov/cgi-bin/rss_outside.pl' },
		{ 'id': 'S.D. Cal.', 'url':'https://ecf.casd.uscourts.gov/cgi-bin/rss_outside.pl' },
		{ 'id': 'D. Colo.', 'url':'https://ecf.cod.uscourts.gov/cgi-bin/rss_outside.pl' },
		{ 'id': 'D. Conn.', 'url':'https://ecf.ctd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'D. Del.', 'url':'https://ecf.ded.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'D.D.C.', 'url':'https://ecf.dcd.uscourts.gov/cgi-bin/rss_outside.pl' },
		{ 'id': 'M.D. Fla.', 'url':'https://ecf.flmd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'S.D. Fla.', 'url':'https://ecf.flsd.uscourts.gov/cgi-bin/rss_outside.pl' },
		{ 'id': 'M.D. Ga.', 'url':'https://ecf.gamd.uscourts.gov/cgi-bin/rss_outside.pl' },
		{ 'id': 'D. Guam', 'url': 'https://ecf.gud.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'D. Idaho', 'url':'https://ecf.idd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'N.D. Ill.', 'url':'https://ecf.ilnd.uscourts.gov/cgi-bin/rss_outside.pl' },
		{ 'id': 'C.D. Ill.', 'url': 'https://ecf.ilcd.uscourts.gov/cgi-bin/rss_outside.pl' },
		{ 'id': 'N.D. Ind.', 'url': 'https://ecf.innd.uscourts.gov/cgi-bin/rss_outside.pl' },
		{ 'id': 'S.D. Ind.', 'url': 'https://ecf.insd.uscourts.gov/cgi-bin/rss_outside.pl' },
		{ 'id': 'N.D. Iowa', 'url':'https://ecf.iand.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'S.D. Iowa', 'url':'https://ecf.iasd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'D. Kan.', 'url':'https://ecf.ksd.uscourts.gov/cgi-bin/rss_outside.pl' },
		{ 'id': 'W.D. Ky.', 'url':'https://ecf.kywd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'E.D. La.', 'url':'https://ecf.laed.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'M.D. La.', 'url':'https://ecf.lamd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'W.D. La.', 'url':'https://ecf.lawd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'D.N.M.I.', 'url': 'https://ecf.nmid.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'D. Maine', 'url': 'https://ecf.med.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'D. Mass.', 'url':'https://ecf.mad.uscourts.gov/cgi-bin/rss_outside.pl' },
		{ 'id': 'E.D. Mich.', 'url': 'https://ecf.mied.uscourts.gov/cgi-bin/rss_outside.pl' },
		{ 'id': 'W.D. Mich.', 'url':'https://ecf.miwd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'S.D. Miss.', 'url': 'https://ecf.mssd.uscourts.gov/cgi-bin/rss_outside.pl' },
		{ 'id': 'E.D. Mo.', 'url':'https://ecf.moed.uscourts.gov/cgi-bin/rss_outside.pl' },
		{ 'id': 'W.D. Mo.', 'url':'https://ecf.mowd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'D. Mont.', 'url':'https://ecf.mtd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'D. Neb.', 'url':'https://ecf.ned.uscourts.gov/cgi-bin/rss_outside.pl' },
		{ 'id': 'D.N.H.', 'url': 'https://ecf.nhd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'D.N.J.', 'url':'https://ecf.njd.uscourts.gov/cgi-bin/rss_outside.pl' },
		{ 'id': 'D.N.M.', 'url': 'https://ecf.nmd.uscourts.gov/cgi-bin/rss_outside.pl' },
		{ 'id': 'E.D.N.Y.', 'url':'https://ecf.nyed.uscourts.gov/cgi-bin/rss_outside.pl' },
		{ 'id': 'N.D.N.Y.', 'url':'https://ecf.nynd.uscourts.gov/cgi-bin/rss_outside.pl' },
		{ 'id': 'S.D.N.Y.', 'url':'https://ecf.nysd.uscourts.gov/cgi-bin/rss_outside.pl' },
		{ 'id': 'E.D.N.C.', 'url':'https://ecf.nhd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'M.D.N.C.', 'url':'https://ecf.ncmd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'W.D.N.C.', 'url': 'https://ecf.ncwd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'E.D. Pa.', 'url':'https://ecf.paed.uscourts.gov/cgi-bin/rss_outside.pl' },
		{ 'id': 'N.D. Ohio', 'url':'https://ecf.ohnd.uscourts.gov/cgi-bin/rss_outside.pl' },
		{ 'id': 'S.D. Ohio', 'url':'https://ecf.ohsd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'W.D. Okla.', 'url':'https://ecf.okwd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'D. Ore.', 'url' : 'https://ecf.ord.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'M.D. Pa.', 'url' : 'https://ecf.pamd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'W.D. Pa.', 'url': 'https://ecf.pawd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'D.P.R.', 'url': 'https://ecf.prd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'D.S.D.', 'url': 'https://ecf.sdd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'E.D. Tenn.', 'url':'https://ecf.tned.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'M.D. Tenn.', 'url':'https://ecf.tnmd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'E.D. Texas', 'url':'https://ecf.txed.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'S.D. Texas', 'url':'https://ecf.txsd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'W.D. Texas', 'url':'https://ecf.txwd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'D.S.D.', 'url': 'https://ecf.sdd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'D. Utah', 'url':'https://ecf.utd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'D. Vt.', 'url':'https://ecf.vtd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'D.V.I.', 'url':'https://ecf.vid.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'W.D. Va.', 'url':'https://ecf.vawd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'E.D. Wash.', 'url':'https://ecf.waed.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'W.D. Wash.', 'url':'https://ecf.wawd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'N.D. W.Va.', 'url':'https://ecf.wvnd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'S.D. W.Va.', 'url':'https://ecf.wvsd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'E.D. Wis.', 'url':'https://ecf.wied.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'W.D. Wis.', 'url':'https://ecf.wiwd.uscourts.gov/cgi-bin/rss_outside.pl'},
		{ 'id': 'D. Wyo.', 'url':'https://ecf.wyd.uscourts.gov/cgi-bin/rss_outside.pl'},

		# Specialty courts
		{ 'id': 'Ct. Cl.', 'url' : 'https://ecf.cofc.uscourts.gov/cgi-bin/rss_outside.pl'},
				
	]
